
export const SET_CURRENT_USER="SET_CURRENT_USER";
export const GET_ERRORS="GET_ERRORS";
export const SET_INVLAID_USER_RESPONSE="SET_INVLAID_USER_RESPONSE";
export const SET_BACKEND_NOT_REACHED="SET_BACKEND_NOT_REACHED";